#!/bin/sh
set -e
set -x

./check_theorems_doc.sh
cd haskell_tool
cabal install --only-dependencies --enable-tests --enable-benchmarks
cabal configure --enable-tests --enable-benchmarks -v2
cabal build
cabal test  --show-details=streaming
