#!/bin/sh
#
# Copyright (C) 2014 NICTA
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions, and the following disclaimer,
#    without modification.
#
# 2. Redistributions in binary form must reproduce at minimum a disclaimer
#    substantially similar to the "NO WARRANTY" disclaimer below
#    ("Disclaimer") and any redistribution must be conditioned upon
#    including a substantially similar Disclaimer requirement for further
#    binary redistribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
# IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED
# TO, THE IMPLIED WARRANTIES OF MERCHANTIBILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDERS OR CONTRIBUTORS BE LIABLE FOR SPECIAL, EXEMPLARY, OR
# CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
# SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
# INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
# CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
# ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF
# THE POSSIBILITY OF SUCH DAMAGES.
#

SEM="../StructSupport.thy ./Arrays.thy ./ArraysMemInstance.thy ./CTypes.thy ./CompoundCTypes.thy ./HeapRawState.thy ./Padding.thy ./x86gcc.thy ./x86gcc_typinfo.thy ./CTypesDefs.thy"
UMM=TypHeap.thy
SEP="Sep*.thy"

echo "Sem Defs `grep const $SEM | wc -l` Thms `grep lemma $SEM | wc -l` LoP `cat $SEM | wc -l `"
echo "UMM Defs `grep const $UMM | wc -l` Thms `grep lemma $UMM | wc -l` LoP `cat $UMM | wc -l `"
echo "Sep Defs `grep const $SEP | wc -l` Thms `grep lemma $SEP | wc -l` LoP `cat $SEP | wc -l `"
